@TmsApi_HostAddress = http://localhost:5298

GET {{TmsApi_HostAddress}}/api/assesments/results/
Accept: application/json

###
GET {{TmsApi_HostAddress}}/api/test/deferred
Accept: application/json

###
GET {{TmsApi_HostAddress}}/api/test/translation-fail
Accept: application/json
###
GET {{TmsApi_HostAddress}}/api/test/translation-fail
Accept: application/json
###
GET {{TmsApi_HostAddress}}/api/students?page=1
Accept: application/json
###
GET {{TmsApi_HostAddress}}/api/test/top-courses
Accept: application/json

### 
PATCH http://localhost:5298/api/students/1?name=Alice+Updated&gpa=3.9&isActive=true
Accept: application/json
###
PATCH http://localhost:5298/api/students/1?name=Alice+FromB
Accept: application/json
###
GET http://localhost:5298/api/courses/1
Accept: application/json
###
GET http://localhost:5298/api/courses/{1}/enrollments=1
Accept: application/json
###
GET http://localhost:5298/api/courses?page=1&pageSize=10
Accept: application/json

###
GET http://localhost:5298/api/courses?page=3&pageSize=10
Accept: application/json

###
GET http://localhost:5298/api/courses?pageSize=999
Accept: application/json

###   
GET http://localhost:5298/api/courses?search=fund
Accept: application/json

###
GET http://localhost:5298/api/courses?orderBy=Code&descending=true&pageSize=5
Accept: application/json

### 
GET  http://localhost:5298/api/v1/courses 

Accept: application/json
###
GET  http://localhost:5298/api/v2/courses 

Accept: application/json
