@TmsApi_HostAddress = http://localhost:5043
GET {{TmsApi_HostAddress}}/api/assessments/results
Accept: application/json


POST {{TmsApi_HostAddress}}/api/test/enroll
###


### 1. GET all — empty array
GET {{TmsApi_HostAddress}}/api/enrollments
X-Training-User: 

###

### 2. POST new enrollment
POST {{TmsApi_HostAddress}}/api/enrollments/
Content-Type: application/json

{
  "studentId": "S-001",
  "courseCode": "CS-101"
}

###

### 3. GET by id (ከ POST response ላይ id ይቅዱ)
GET {{TmsApi_HostAddress}}/api/enrollments/08c774f9
X-Training-User: 

###

### 4. DELETE
DELETE {{TmsApi_HostAddress}}/api/enrollments/
X-Training-User: 

###

### 5. GET deleted (404 )
GET {{TmsApi_HostAddress}}/api/enrollments/08c774f9
X-Training-User: 

###
// student
### GET all students
GET {{TmsApi_HostAddress}}/api/students

###

### POST new student
POST {{TmsApi_HostAddress}}/api/students
Content-Type: application/json

{
  "firstName": "Tewolde",
  "lastName": "Tesfaye",
  "email": "tolatesfaye30.com"
}

###

### GET student by id (use id from POST response)
GET {{TmsApi_HostAddress}}/api/students/{id-here}

###

### DELETE student
DELETE {{TmsApi_HostAddress}}/api/students/{id-here}


// Course

### GET all courses
GET {{TmsApi_HostAddress}}/api/courses

###

### POST new course
POST {{TmsApi_HostAddress}}/api/courses
Content-Type: application/json

{
  "courseCode": "CS-102",
  "title": "Fun Programming",
  "credits": 3
}

###

### GET course by id (use id from POST response)
GET {{TmsApi_HostAddress}}/api/courses/b310f0f9

###

### DELETE course
DELETE {{TmsApi_HostAddress}}/api/courses/b310f0f9